CREATE TABLE [dbo].[CLIENTE]
(
[CODCLI] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DNICLI] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[NOMCLI] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[APECLI] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CELCLI] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[EMACLI] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FECNACCLI] [date] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLIENTE] ADD CONSTRAINT [CODCLI_PK] PRIMARY KEY CLUSTERED  ([CODCLI]) ON [PRIMARY]
GO
