CREATE TABLE [dbo].[VENDEDOR]
(
[CODVEN] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DNIVEN] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[NOMVEN] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[APEVEN] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CELVEN] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[EMAVEN] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FECNACVEN] [date] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENDEDOR] ADD CONSTRAINT [CODVEN_PK] PRIMARY KEY CLUSTERED  ([CODVEN]) ON [PRIMARY]
GO
